testing/sd_*: Restrict function and variable scope to current file.
apache/nuttx-apps pull request #2201
Opened 2023-11-17 04:40 UTC by g2gps

## Summary

Add the static keyword to required function and variable delcaration to reduce their scope. Stops namespace pollution in `CONFIG_BUILD_FLAT`

## Impact

Stops symbol collision when `CONFIG_TESTING_SD_BENCH` and `CONFIG_TESTING_SD_STRESS` are enables simultaneously. 

## Testing

Enable `CONFIG_TESTING_SD_BENCH` and `CONFIG_TESTING_SD_STRESS` at the same time.

2023-11-17 06:52 UTC, xiaoxiang781216 commented on testing/sd_bench/sd_bench_main.c
>                          const struct timespec *end)
```suggestion
                                 const struct timespec *end)
```

2023-11-17 06:52 UTC, xiaoxiang781216 commented on testing/sd_stress/sd_stress_main.c
>                          const struct timespec *end)
```suggestion
                              const struct timespec *end)
```

2023-11-17 06:55 UTC, davids5 requested changes
Why not allocate these in a struct and reduce memory footprint that just including that app costs?

2023-11-17 13:47 UTC, pkarashchenko commented
> Why not allocate these in a struct and reduce memory footprint that just including that app costs?

Could you please expand more with maybe a kind of example. I'm not fully following your proposal. I think all those local `const`s will be optimized out by compiler anyway.

2023-11-17 16:23 UTC, hartmannathan approved these changes

2023-11-20 14:13 UTC, davids5 commented
Yokogawa 700937 

> > Why not allocate these in a struct and reduce memory footprint that just including that app costs?
> 
> Could you please expand more with maybe a kind of example. I'm not fully following your proposal. I think all those local `static const`s will be optimized out by compiler anyway.

I did not think these were local. Also as globals they  do not conform to the coding standard. 

My point was placing all the variables in a struct allocated at run time will reduce the data size to a single pointer or 0 if it is passed as an argument.

2024-04-29 20:31 UTC, acassis commented
ping @g2gps

2024-05-08 05:42 UTC, g2gps commented
Sorry, I'd forgotten that this was pending.

These variables are marked static, so if I understand correctly, there scope is limited to the files the file they are declared in. 

There is an opportunity to reduce the scope of some of these variables, if required I can refactor.

2024-05-08 08:42 UTC, xiaoxiang781216 approved these changes

2024-05-08 08:52 UTC, merged