`i2ctool dev` command now uses an empty write header to scan the I2C bus
apache/nuttx-apps pull request #2447
Opened 2024-07-18 00:07 UTC by linguini1

## Summary

The `i2ctool dev` command will now use an empty 'write' header to scan the I2C bus by default (if no register is provided), which results in the detection of more I2C devices by default (including the SHT41 and MS5611).

This PR closes #994.

## Impact

This should save some developers time debugging or wondering why their devices didn't show up (and trying to wrongly diagnose a hardware issue like myself :laughing:).

## Testing

Using the previous version of this command on an I2C bus with the following sensors:

- MS5611 barometric pressure sensor (2, at 0x76 and 0x77)
- SHT41 temperature and humidity sensor (0x44)
- MAXM10S GPS (0x42)
- M24C02 EEPROM (0x50)
- LSM6DSO32 IMU (0x6b)

The output of `i2c dev 00 77` was:

```console
nsh> i2c dev 00 77
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: 00 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- 42 -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: 50 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- 6b -- -- -- -- 
70: -- -- -- -- -- -- -- --                         
```

Even providing an argument to the register flag (`i2c dev -r 0 00 77`) resulted in the saem output.

With these proposed changes, the result by default is:

```console
nsh> i2c dev 00 77
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- 42 -- 44 -- -- -- -- -- -- -- -- -- -- -- 
50: 50 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- 6b -- -- -- -- 
70: -- -- -- -- -- -- 76 77
```

Now all devices show up in the scan. Additionally, the general call address of `00` does not appear anymore, which is good as it is not a real device.

2024-07-18 05:44 UTC, xiaoxiang781216 approved these changes

2024-07-18 05:45 UTC, xiaoxiang781216 approved these changes

2024-07-18 10:30 UTC, davids5 requested changes
Is this safe or will it over write values.
Do all the archs support 0 length writes and actually make it to the bus?

2024-07-18 12:50 UTC, acassis approved these changes

2024-07-18 14:19 UTC, linguini1 commented
> @linguini1 did you test i2ctools on Linux and look at logic analyzer? Let's confirm Linux also do this way.

I won't have a change to access a logic analyzer for a little while. I had a look at the description for the Linux I2C tools here:

https://github.com/MLAB-project/i2c-tools/blob/master/tools%2Fi2cdetect.8

It seems they either use a single byte read (as was the previous implementation) or a write command, depending on the address by default. Although they do warn that scanning the bus can affect the I2C devices since there is no actual standard for scanning in the I2C protocol.

2024-07-18 19:47 UTC, acassis commented
> > @linguini1 did you test i2ctools on Linux and look at logic analyzer? Let's confirm Linux also do this way.
> 
> I won't have a change to access a logic analyzer for a little while. I had a look at the description for the Linux I2C tools here:
> 
> https://github.com/MLAB-project/i2c-tools/blob/master/tools%2Fi2cdetect.8
> 
> It seems they either use a single byte read (as was the previous implementation) or a write command, depending on the address by default. Although they do warn that scanning the bus can affect the I2C devices since there is no actual standard for scanning in the I2C protocol.
> 
> Perhaps a good compromise would be trying to read one byte from the address, and if that fails, attempt to send a 0 byte write?

I'm curious to know if Linux i2ctool is able to detect these sensors.

@linguini1 maybe to avoid David's worryings (in fact it could break I2C for arch that don't work when msgc is 0 or msg is NULL), I suggest you implementing your suggestion as special search case (like -z for zero byte reading).

2024-07-18 20:24 UTC, linguini1 commented
> @linguini1I suggest you implementing your suggestion as special search case (like -z for zero byte reading).

Do you think it would be worth while for the i2ctool to have some `#ifdef` to check the architecture and disable the -z functionality for architectures which do not support the 0 byte write?

2024-07-18 21:46 UTC, cederom commented
> > @linguini1I suggest you implementing your suggestion as special search case (like -z for zero byte reading).
> 
> Do you think it would be worth while for the i2ctool to have some `#ifdef` to check the architecture and disable the -z functionality for architectures which do not support the 0 byte write?

+ verbose message in either situation could be helpful..?

2024-07-18 21:55 UTC, acassis commented
> > @linguini1I suggest you implementing your suggestion as special search case (like -z for zero byte reading).
> 
> Do you think it would be worth while for the i2ctool to have some `#ifdef` to check the architecture and disable the -z functionality for architectures which do not support the 0 byte write?

I don't think we can check the architecture now, because we don't know which arch will fail and which will work. My suggestion for now is adding the "-z" and maybe include a suggestion just before the scan start:

If your device didn't appear in the bus, try to use the -z option

2024-07-20 03:17 UTC, linguini1 commented
@davids5 As far as I can tell, this should be safe. A 0 byte write means that any sensors which allow a write with no register address first specified should not perform the write regardless, since there is no data sent to be written. A device should see the stop condition and discard the write request, but I suppose it is possible for a poorly designed device to not handle this case.

Architectures which do not support a 0 byte write through their I2C driver will return some error, which will cause any device to just not appear. This is fine since with the addition of the `-z` option, the default behaviour is still a single byte read. The `-z` is a fallback for the user to check in case they do not see their expected device appearing in the scan.

Please let me know if there's anything I've overlooked!

2024-07-20 05:12 UTC, xiaoxiang781216 approved these changes
LGTM.

2024-07-20 05:13 UTC, xiaoxiang781216 commented
@davids5 the patch look fine since zero write is guarded by option in the new change.

2024-07-20 08:40 UTC, davids5 approved these changes
The option mitigates my concern. Thank you

2024-07-20 11:51 UTC, merged