enable SOCK_CLOEXEC explicit
apache/nuttx-apps pull request #2595
Opened 2024-09-21 13:58 UTC by gneworld

## Summary
 leaking here means fork/vfork will duplicate fd without O_CLOEXEC flag to the child process.
## Impact
 net apps and utils
## Testing

2024-09-21 15:04 UTC, xiaoxiang781216 approved these changes

2024-09-21 16:34 UTC, cederom approved these changes
Thank you @gneworld :-)

2024-09-21 16:36 UTC, cederom commented
What about macOS and xtensa build errors?

2024-09-22 01:30 UTC, gneworld commented
> What about macOS and xtensa build errors?

@cederom 

  Cleaning...
  Configuring...
  Building NuttX...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  340k  100  340k    0     0  1179k      0 --:--:-- --:--:-- --:--:-- 1179k
fatal: unable to access 'https://github.com/espressif/esp-phy-lib.git/': gnutls_handshake() failed: Error in the pull function.
fatal: Fetched in submodule path 'components/esp_phy/lib', but it did not contain 06e7625de197bc12797dd701d6762229bca01826. Direct fetching of that commit failed.
fatal: 
make[1]: *** [chip/Make.defs:269: context] Error 128
make: *** [tools/Unix.mk:457: arch/xtensa/src/.context] Error 2
make: Target 'all' not remade because of errors.
/github/workspace/sources/nuttx/tools/testbuild.sh: line 385: /github/workspace/sources/nuttx/../nuttx/nuttx.manifest: No such file or directory
  Normalize esp32s3-korvo-2/audio
====================================================================================
Configuration/Tool: esp32s3-meadow/usbnsh

@cederom 

xtensa  build errors is caused by  "unable to access 'https://github.com/espressif/esp-phy-lib.git/' "
macOS build errors is caused by  that "accept4" and  SOCK_CLOEXEC are Linux-specific system calls and macro definitions.
I have isolated them using the __APPLE__  preprocessor directive.

2024-09-22 01:53 UTC, cederom requested changes
Lets make sure code is portable and does not depend on any Linux specific calls, that would prevent build / run on other operating systems.

2024-09-22 02:02 UTC, cederom commented
@gneworld can you please update the PR description / Testing with boards:configurations used to verify the change (what parameters was used for `tools/configure.sh`)? Have you tested / aimed this change for sim and/or boards?

I will try to build the change on FreeBSD just to make sure things work here too. `man accept4` and `/usr/include/sys/socket.h` indicates its presence here.

Strange its not on macOS. We also need to verify windoze.

2024-09-22 09:01 UTC, gneworld commented
@cederom 
After solving another file descriptor leak issue, I took the opportunity to modify all the code that has this potential vulnerability. 
As far as I know, NuttX currently doesn't  support compilation on Windows (excluding WSL), right?

2024-09-22 13:58 UTC, cederom commented
> @cederom After solving another file descriptor leak issue, I took the opportunity to modify all the code that has this potential vulnerability. 

Great thank you @gneworld :-) 

> As far as I know, NuttX currently doesn't support compilation on Windows (excluding WSL), right?

Yes build on Windoze is possible, `msys2` CI builder does the job :-) Looks like it passed correctly :-)

2024-09-22 14:01 UTC, cederom commented
I am wondering how to solve macOS issue - for now the security related fix seems skipped on macOS that produces inconsistent build behavior depending on the build platform. Maybe @lupyuen can help us here as macOS user? :-)

2024-09-23 00:35 UTC, xiaoxiang781216 approved these changes

2024-09-23 02:44 UTC, lupyuen commented
@cederom Sorry don't think I can help much. I'm a macOS User, I hardly code apps for macOS :-)

2024-09-23 03:34 UTC, cederom commented
> @cederom Sorry don't think I can help much. I'm a macOS User, I hardly code apps for macOS :-)

Would it be possible to try to build the PR on your machine and confirm the problem? Note `__APPLE__` ifdef that currently "hides" the issue. Question is why macOS does not have `accept4` implemented even if other Unix like OS have it :-)

2024-09-23 03:45 UTC, cederom commented
Here is some reference on difference between `accept` and `accept4` [1]:

> accept4 is a non-standard linux extension. The real difference is in the 4th argument (flags) which is not present in accept.

>  If flags is 0, then accept4() is the same as accept(). The following values can be bitwise ORed in flags to obtain different behavior:

> `SOCK_NONBLOCK` Set the `O_NONBLOCK` file status flag on the new open                        file description.  Using this flag saves extra calls to fcntl(2) to achieve the same result.

> `SOCK_CLOEXEC` Set the close-on-exec (`FD_CLOEXEC`) flag on the new                        file descriptor.  See the description of the `O_CLOEXEC` flag in open(2) for reasons why this may be useful.

>  By default, the new file descriptor is set to remain open across an execve(2) (i.e., the FD_CLOEXEC file descriptor flag described in fcntl(2) is initially disabled); the O_CLOEXEC flag, described below, can be used to change this default.

> And for eg, by using this flag (SOCK_CLOEXEC), one can avoid race conditions in multithreaded programs where it may lead to the file descriptor returned by open() being unintentionally leaked to the program executed by the child process created by fork(2).

Let me find some macOS machine.. and find the `accept4` in the headers anywhere.. if there is none then @gneworld solution to wrap the call seems the only one possible :-)

[1] https://stackoverflow.com/questions/23952794/what-the-difference-between-accept4-and-accept

2024-09-23 04:03 UTC, xiaoxiang781216 commented
@cederom the implementation of accept4 comes from nuttx, not ffrom host OS. BTW all CI already pass now.

2024-09-23 04:06 UTC, cederom commented
Okay quick check reveals:
* `accept` is part of ` POSIX.1-2008` standard (history: POSIX.1-2001, SVr4, 4.4BSD, first appeared in 4.2BSD).
* `accept4` is not standard compliant Linux extension but offers increased security (history: Linux 2.6.28, glibc 2.10).
* Even my FreeBSD has `accept4` defined in `/usr/include/sys/syscall.h`.
* macOS does not seem to have `accept4` syscall implemented. The only place I found was GoLang internal implementation, and some Perl and Python checks if system supports it.
* We have no other way than to use more secure `accept4` on systems that supports it and fallback to `accept` on systems that don't :-)

2024-09-23 04:09 UTC, lupyuen commented
FYI @cederom I was able to reproduce the accept4 build error on macOS Arm64 14.6.1 (23G93):

```text
$ tools/configure.sh bl602evb:wifi
$ make -j
CC:  nettest_server.c
nettest_server.c:152:2: warning: NOT_APPLE ////  [-W#warnings]
  152 | #warning NOT_APPLE //// 
      |  ^
nettest_server.c:153:14: error: call to undeclared function 'accept4'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  153 |   acceptsd = accept4(listensd, (struct sockaddr *)&myaddr, &addrlen,
      |              ^
nettest_server.c:153:14: note: did you mean 'accept'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/socket.h:708:9: note: 'accept' declared here
  708 | int     accept(int, struct sockaddr * __restrict, socklen_t * __restrict)
      |         ^
nettest_server.c:154:22: error: use of undeclared identifier 'SOCK_CLOEXEC'
  154 |                      SOCK_CLOEXEC);
      |                      ^
```

And accept4 doesn't exist in MacOSX.sdk/usr/include/sys/socket.h

2024-09-23 04:09 UTC, cederom commented
> @cederom the implementation of accept4 comes from nuttx, not from host OS. BTW all CI already pass now.

Yes I can see it in `include/sys/socket.h`, `net/socket/accept.c` etc if we use internal one then even better :-) Was wondering why build failed on macOS, turns out it has no implementation (was used for sim or what?) :D

2024-09-23 04:11 UTC, cederom commented
> FYI @cederom I was able to reproduce the [accept4 build error](https://github.com/apache/nuttx-apps/actions/runs/10973134118/job/30470198826) on macOS Arm64 14.6.1 (23G93):
> 
> ```
> $ tools/configure.sh bl602evb:wifi
> $ make -j
> CC:  nettest_server.c
> nettest_server.c:152:2: warning: NOT_APPLE ////  [-W#warnings]
>   152 | #warning NOT_APPLE //// 
>       |  ^
> nettest_server.c:153:14: error: call to undeclared function 'accept4'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
>   153 |   acceptsd = accept4(listensd, (struct sockaddr *)&myaddr, &addrlen,
>       |              ^
> nettest_server.c:153:14: note: did you mean 'accept'?
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/socket.h:708:9: note: 'accept' declared here
>   708 | int     accept(int, struct sockaddr * __restrict, socklen_t * __restrict)
>       |         ^
> nettest_server.c:154:22: error: use of undeclared identifier 'SOCK_CLOEXEC'
>   154 |                      SOCK_CLOEXEC);
>       |                      ^
> ```
> 
> And accept4 doesn't exist in MacOSX.sdk/usr/include/sys/socket.h

Thank you @lupyuen !! :-) So this check was done without the fallback wrap `__APPLE__` and with the fallback all builds fine? :-)

2024-09-23 04:12 UTC, lupyuen commented
> So this check was done without the fallback wrap `__APPLE__` and with the fallback all builds fine? :-)

@cederom Yep the fallback works fine.

2024-09-23 04:14 UTC, cederom approved these changes
Thank you @gneworld :-)

2024-09-23 04:15 UTC, cederom commented
> > So this check was done without the fallback wrap `__APPLE__` and with the fallback all builds fine? :-)
> 
> @cederom Yep the fallback works fine.

@lupyuen TANK U SIR!! =)

2024-09-23 04:43 UTC, xiaoxiang781216 commented
> > FYI @cederom I was able to reproduce the [accept4 build error](https://github.com/apache/nuttx-apps/actions/runs/10973134118/job/30470198826) on macOS Arm64 14.6.1 (23G93):
> > ```
> > $ tools/configure.sh bl602evb:wifi
> > $ make -j
> > CC:  nettest_server.c
> > nettest_server.c:152:2: warning: NOT_APPLE ////  [-W#warnings]
> >   152 | #warning NOT_APPLE //// 
> >       |  ^
> > nettest_server.c:153:14: error: call to undeclared function 'accept4'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
> >   153 |   acceptsd = accept4(listensd, (struct sockaddr *)&myaddr, &addrlen,
> >       |              ^
> > nettest_server.c:153:14: note: did you mean 'accept'?
> > /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/socket.h:708:9: note: 'accept' declared here
> >   708 | int     accept(int, struct sockaddr * __restrict, socklen_t * __restrict)
> >       |         ^
> > nettest_server.c:154:22: error: use of undeclared identifier 'SOCK_CLOEXEC'
> >   154 |                      SOCK_CLOEXEC);
> >       |                      ^
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And accept4 doesn't exist in MacOSX.sdk/usr/include/sys/socket.h
> 
> Thank you @lupyuen !! :-) So this check was done without the fallback wrap `__APPLE__` and with the fallback all builds fine? :-)

it's temp macOS ci error.

2024-09-23 11:29 UTC, cederom commented
Hmm, looks more like macOS, as Lup was able to reproduce outside CI.. maybe some includes are missing to reference internal implementation? o_O

2024-09-26 08:13 UTC, merged

2024-09-29 20:32 UTC, pkarashchenko commented
I've noticed warnings on the CI builds
```
nettest_server.c: In function 'nettest_server':
Warning: nettest_server.c:151:14: warning: implicit declaration of function 'accept4'; did you mean 'accept'? [-Wimplicit-function-declaration]
  151 |   acceptsd = accept4(listensd, (struct sockaddr *)&myaddr, &addrlen,
      |              ^~~~~~~
      |              accept
  Normalize c5471evm/nettest
```

2024-09-29 20:47 UTC, cederom commented
Yeah I noticed that too @pkarashchenko  all following builds have this warning please provide fix in separate PR @gneworld :-)

2024-09-30 06:46 UTC, xiaoxiang781216 commented
it's strange that ci doesn't catch this warning.

2024-09-30 08:13 UTC, pkarashchenko commented
> it's strange that ci doesn't catch this warning.

CI produce warning, but warning is not treated as error for that build