testing/drivertest_block.c: Fix cmoka driver block test error
apache/nuttx-apps pull request #2693
Opened 2024-10-11 14:05 UTC by wyr-7

## Summary
testing/drivertest_block.c: Fix cmoka driver block test error
## Impact
1. Fix the problem that pre->source may have memory stampede
2. Fix total block size larger than cache size condition
## Testing
Test in Vela

2024-10-11 14:19 UTC, nuttxpr commented
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



This pull request appears to **partially meet** the NuttX requirements. Here's a breakdown:

**Strengths:**

* **Summary:** Provides a clear and concise description of the issue addressed (memory stampede, block size exceeding cache size) and the file affected (`testing/drivertest_block.c`). 
* **Impact:**  Clearly outlines the functional impact of the changes (fixing errors).
* **Testing:**  Indicates the testing environment (Vela), but lacks specific details.

**Areas for improvement:**

* **Summary:**
    *  Lacks a related issue reference if this PR addresses a known bug. 
* **Impact:**
    *  The impact section is very brief. While it mentions fixes, it lacks details about potential user impact, build process changes, hardware dependencies, or documentation requirements. 
    * All other impact points are not addressed. While they may not be relevant, explicitly stating "NO" with a brief justification (e.g., "No impact on build process as changes are isolated to testing code") would provide a more thorough assessment.
* **Testing:**
   * **Crucially**, it lacks testing logs before and after the change.  These logs are essential to demonstrate the actual issue and the effectiveness of the fix. 

**Recommendation:**

To fully meet the NuttX requirements, the PR should include:

1. **Related Issue:** If applicable, link the corresponding NuttX issue that this PR addresses.
2. **Detailed Impact Assessment:**  Address all impact points, even if the answer is "NO."  Briefly explain why there is no impact for each point.
3. **Complete Testing Information:** Provide the complete testing logs **before** and **after** the change to clearly demonstrate the fix. This includes:
   *  Build host details: OS, CPU architecture, compiler version.
   * Target details: Architecture (e.g., sim, RISC-V, ARM), board configuration.
   * Relevant log snippets showing the error before the fix and the corrected behavior after. 

By addressing these points, the PR will be more comprehensive and easier for reviewers to assess.

2024-10-11 21:33 UTC, cederom requested changes
Thank you @wyr-7 :-) Build errors reveal minor tweaks are required :-)

2024-10-14 18:56 UTC, xiaoxiang781216 commented on testing/drivertest/drivertest_block.c
> +      printf("Warning: Total block size too small, need larger than %ld\n",
```suggestion
      printf("Warning: Total block size too small, need larger than %" PRId32 "\n",
```

2024-10-15 23:18 UTC, xiaoxiang781216 approved these changes

2024-10-15 23:18 UTC, merged