app/system/vi: Fix broken VI editor
apache/nuttx-apps pull request #2769
Opened 2024-10-25 01:34 UTC by bl4kraven

## Summary

1. Since Nuttx commit https://github.com/apache/nuttx/commit/df5c876932c4c82e8aee32adca651bb99d9d6200 , the serial driver enable ICANON flag as default. This broken the VI and all keystrokes inputs are buffered. So disable it in termcurses.

2. If the VI exits in an error condition it will break the console.  This is because release_vi was not called to restore the console configuration, so fix it.

## Impact

All VI-enabled boards.

## Testing

Test in Ubuntu 24.20 use sim:nsh.

2024-10-25 01:39 UTC, nuttxpr commented
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



The PR summary you provided lacks some key details to determine if it meets the NuttX requirements. Here's a breakdown and what needs improvement:

**Strengths:**

* **Clear problem statements:** Both points in the summary clearly identify the issue being addressed.
* **Impact is addressed:** It broadly identifies affected boards.

**Weaknesses:**

* **Missing details about the change itself:**  
    * The summary only describes the *problem* not the *solution*. How exactly are you disabling ICANON in termcurses?  What code is modified?
    * How is `release_vi` being incorporated to fix the error condition exit?
* **Impact section is too vague:**
    * "All VI-enabled boards" is not specific enough. Which architectures?  Are there known boards where this *won't* be an issue?
    * The other impact categories are completely skipped. At minimum, address:
        * **Build:**  Did the build process change at all due to your modifications?
        * **Documentation:** Does this fix require any documentation updates?
* **Testing is insufficient:**
    * **Only one host/target combination:**  NuttX supports a wide range of platforms. Testing on a single simulated environment is not enough.
    * **No logs provided:**  The "Testing logs" sections are empty, making it impossible to verify the fix. 

**To meet NuttX requirements, the PR needs these improvements:**

1. **Elaborate on the solution:**  Don't just describe the problem. Explain the code changes made to implement the fix.
2. **Be specific about impact:**  List affected architectures and, if possible, any boards known to be *unaffected*. Address all other impact categories.
3. **Expand testing:** 
    * Test on at least one more significantly different target (e.g., a real board if you initially tested on simulator).
    * **Include relevant logs:**  Show output *before* and *after* your change to demonstrate the fix.

By addressing these points, the PR will be much stronger and more likely to be accepted.

2024-10-25 01:57 UTC, xiaoxiang781216 commented on system/termcurses/tcurses_vt100.c
> +              if (cfg.c_lflag & ICANON)
let's merge with block line 1505-1509:
```
if (cfg.c_lflag & (ECHO | ICANON))
  {
    cfg.c_lflag &= ~(ECHO | ICANON);
    tcsetattr(priv->in_fd, TCSANOW, &cfg);
  }
```

2024-10-25 01:57 UTC, xiaoxiang781216 commented on system/termcurses/tcurses_vt100.c
> -          if (tcgetattr(priv->in_fd, &cfg) == 0 && priv->lflag & ECHO)
```
          if ((priv->lflag & (ECHO | ICANON)) && tcgetattr(priv->in_fd, &cfg) == 0)
            {
              cfg.c_lflag = priv->lflag;
              tcsetattr(priv->in_fd, TCSANOW, &cfg);
           }
```

2024-10-25 02:27 UTC, bl4kraven commented on system/termcurses/tcurses_vt100.c
> +              if (cfg.c_lflag & ICANON)
Thanks, i will fix it.

2024-10-25 02:27 UTC, bl4kraven commented on system/termcurses/tcurses_vt100.c
> -          if (tcgetattr(priv->in_fd, &cfg) == 0 && priv->lflag & ECHO)
Thanks, i will fix it.

2024-10-25 02:28 UTC, bl4kraven commented
OK thanks, i fix it.

2024-10-25 07:42 UTC, xiaoxiang781216 approved these changes

2024-10-26 22:09 UTC, acassis approved these changes

2024-10-28 00:22 UTC, jerpelea approved these changes

2024-10-28 02:33 UTC, bl4kraven commented
OK, It's already fixed.

2024-10-28 02:40 UTC, cederom requested changes
```
Error: /home/runner/work/nuttx-apps/nuttx-apps/apps/system/termcurses/tcurses_vt100.c:1549:46: error: Dangling whitespace at the end of line
Error: Process completed with exit code 1.
```

2024-10-28 03:31 UTC, bl4kraven commented
OK, It's already fixed.

2024-10-28 05:01 UTC, xiaoxiang781216 approved these changes

2024-10-28 05:58 UTC, cederom approved these changes
Perfect! Thank you @bl4kraven :-)

2024-10-28 13:10 UTC, merged